export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  TEAM: '/team',
  MEMBERS: '/members',
  NOTICES: '/notices',
  NOTICE_DETAIL: '/notices/:slug',
  LEGAL_UPDATES: '/legal-updates',
  LEGAL_UPDATE_DETAIL: '/legal-updates/:slug',
  DOCUMENTS: '/documents',
  GALLERY: '/gallery',
  CONTACT: '/contact',
  LINKS: '/links',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_SIGNUP: '/admin/signup',
  ADMIN_FORGOT_PASSWORD: '/admin/forgot-password',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_NOTICES: '/admin/notices',
  ADMIN_LEGAL_UPDATES: '/admin/legal-updates',
  ADMIN_DOCUMENTS: '/admin/documents',
  ADMIN_GALLERY: '/admin/gallery',
  ADMIN_LINKS: '/admin/links',
  ADMIN_TEAM: '/admin/team',
  ADMIN_MEMBERS: '/admin/members',
  ADMIN_CONTACT_SUBMISSIONS: '/admin/contact-submissions',
  ADMIN_PROFILE: '/admin/profile'
};
